# This is a basic workflow to help you get started with Actions
name: deploy
on: [push]

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - run: echo "Ejecutamos nuestro workflow.."
